import React, { Component } from 'react';

/**Components*/
import Header from './components/Header'
import CourseList from './components/CourseList'

/**
 * Use the App component (src/App.js file) that was generated by the create-react-app tool as your main container component.
 */
class App extends Component {
  render(){
      return(
          <div>
               <Header />
               <CourseList />
          </div>
      )
  }
}

export default App;
